[package]
name = "wb-notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
smol = "2.0.0"
postcard = { version = "1.0.8", default_features = false, features = [ "use-std" ] }
postcard-rpc = { version = "0.3.1", default-features = false }
wb-notifier-client = { path = "./client" }
wb-notifier-proto = { path = "./proto" }
wb-notifier-server = { path = "./server" }

[[bin]]
name = "wbn-client"
path = "src/bin/client.rs"

[workspace]
members = [ "client", "driver", "proto", "server" ]

[profile.release]
opt-level = "z"
